#logging.config=classpath:log4j.xml
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 203031
        url: jdbc:mysql://localhost:3306/class_test?useSSL=false&useUnicode=true&characterEncoding=utf-8

logging:
    level:
        com:
            lcl:
                donation:
                    mapper: debug
#    config: classpath:log4j.xml
#debug: true